const STORAGE_KEY='python-lab-progress-v3';
const lessons=[
  {id:'hello',icon:'&#9889;',title:'你好，Python！',description:'认识 print()，向程序世界发送第一条信号。',concepts:['print()','字符串','程序输出'],knowledge:'<code>print()</code> 会把括号中的内容显示在终端。文本需要放在引号中。',mission:'输出完全一致的文字：你好，Python！',checklist:['使用 print()','包含“你好，Python！”','输出内容完全正确'],starter:'# 向 Python 世界发送第一条信号\nprint("你好，Python！")',solution:'print("你好，Python！")',hint:'文本要放在引号里：<code>print("...")</code>',reward:60,test:(code,out)=>[/print\s*\(/.test(code),/你好，Python！/.test(code),out.trim()==='你好，Python！']},
  {id:'variables',icon:'&#9670;',title:'变量能量舱',description:'用变量保存名字和等级，再组合输出一段自我介绍。',concepts:['变量','字符串','整数','f-string'],knowledge:'变量像有名字的容器。<code>name = "Nova"</code> 保存文本，<code>level = 1</code> 保存数字。',mission:'创建 name="Nova" 和 level=1，输出：Nova is level 1',checklist:['创建 name 变量','创建 level 变量','正确组合并输出'],starter:'name = "Nova"\nlevel = 1\n\n# 使用 f-string 输出自我介绍\nprint(f"{name} is level {level}")',solution:'name = "Nova"\nlevel = 1\nprint(f"{name} is level {level}")',hint:'f-string 写法：<code>f"{变量} text {变量}"</code>',reward:70,test:(code,out)=>[/name\s*=\s*["\']Nova["\']/.test(code),/level\s*=\s*1/.test(code),out.trim()==='Nova is level 1']},
  {id:'condition',icon:'&#9672;',title:'条件判断门',description:'让程序根据能量值做出不同决定。',concepts:['if','else','比较运算'],knowledge:'<code>if</code> 检查条件；条件成立运行缩进代码，否则进入 <code>else</code>。',mission:'energy=80。当能量大于等于 60 时输出 Launch，否则输出 Recharge。',checklist:['定义 energy=80','使用 if 和 else','输出 Launch'],starter:'energy = 80\n\nif energy >= 60:\n    print("Launch")\nelse:\n    print("Recharge")',solution:'energy = 80\nif energy >= 60:\n    print("Launch")\nelse:\n    print("Recharge")',hint:'比较“大于等于”使用 <code>&gt;=</code>，别忘记冒号和缩进。',reward:80,test:(code,out)=>[/energy\s*=\s*80/.test(code),/if\s+energy\s*>=\s*60\s*:/.test(code)&&/else\s*:/.test(code),out.trim()==='Launch']},
  {id:'loop',icon:'&#8635;',title:'循环推进器',description:'用循环重复任务，不再复制粘贴代码。',concepts:['for','range()','循环变量'],knowledge:'<code>range(1, 4)</code> 产生 1、2、3，<code>for</code> 会依次处理它们。',mission:'使用 for 和 range 输出 1、2、3，每个数字一行。',checklist:['使用 for 循环','使用 range(1, 4)','按顺序输出三行'],starter:'for number in range(1, 4):\n    print(number)',solution:'for number in range(1, 4):\n    print(number)',hint:'结构是 <code>for number in range(1, 4):</code>，下一行需要缩进。',reward:90,test:(code,out)=>[/for\s+\w+\s+in\s+range\s*\(/.test(code),/range\s*\(\s*1\s*,\s*4\s*\)/.test(code),out.trim()==='1\n2\n3']},
  {id:'function',icon:'&#9711;',title:'函数制造台',description:'封装可重复使用的逻辑，制造自己的工具。',concepts:['def','参数','return'],knowledge:'函数用 <code>def</code> 定义，通过参数接收数据，用 <code>return</code> 返回结果。',mission:'定义 double(number)，返回 number*2，并输出 double(6) 的结果。',checklist:['定义 double 函数','使用 return','输出 12'],starter:'def double(number):\n    return number * 2\n\nprint(double(6))',solution:'def double(number):\n    return number * 2\n\nprint(double(6))',hint:'函数第一行：<code>def double(number):</code>，return 需要缩进。',reward:100,test:(code,out)=>[/def\s+double\s*\(\s*number\s*\)\s*:/.test(code),/return\s+number\s*\*\s*2/.test(code),out.trim()==='12']},
  {id:'project',icon:'&#9733;',title:'终极任务：猜数字',description:'综合变量、条件和输入，完成第一个小游戏核心。',concepts:['input()','int()','条件分支'],knowledge:'<code>input()</code> 获取文字输入，<code>int()</code> 把数字文字转换为整数。自动测试会输入 7。',mission:'secret=7，读取 guess；猜中输出 Correct!，否则输出 Try again。',checklist:['定义 secret=7','读取并转换 guess','正确判断并输出'],starter:'secret = 7\nguess = int(input())\n\nif guess == secret:\n    print("Correct!")\nelse:\n    print("Try again")',solution:'secret = 7\nguess = int(input())\nif guess == secret:\n    print("Correct!")\nelse:\n    print("Try again")',hint:'自动测试输入是 7。使用 <code>guess == secret</code> 判断是否相等。',reward:130,input:'7',test:(code,out)=>[/secret\s*=\s*7/.test(code),/int\s*\(\s*input\s*\(/.test(code),out.trim()==='Correct!']}
];

let state=loadState();
let selected=Math.min(state.current||0,lessons.length-1);
let worker=null,requestId=0,pending=new Map(),runtimeLoaded=false,isRunning=false;
const $=id=>document.getElementById(id);

function loadState(){try{const saved={xp:0,runs:0,completed:[],code:{},current:0,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')};if(saved.code?.hello?.includes('Hello, Python!'))saved.code.hello=saved.code.hello.replaceAll('Hello, Python!','你好，Python！');return saved}catch{return{xp:0,runs:0,completed:[],code:{},current:0}}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));updateStats()}
function isUnlocked(index){return index===0||state.completed.includes(lessons[index-1].id)}
function currentLesson(){return lessons[selected]}
function level(){return Math.floor(state.xp/200)+1}
function escapeHtml(text){return text.replace(/[&<>]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[ch]))}

function renderNav(){
  $('lessonNav').innerHTML=lessons.map((lesson,index)=>{const done=state.completed.includes(lesson.id),unlocked=isUnlocked(index);return `<button class="lesson-button ${index===selected?'active':''} ${done?'done':''} ${unlocked?'':'locked'}" data-index="${index}" type="button"><i>${done?'&#10003;':String(index+1).padStart(2,'0')}</i><div><h4>${lesson.title}</h4><p>${done?'已完成':unlocked?'可以开始':'请先完成上一关'}</p></div><span>${unlocked?'&#8594;':'&#128274;'}</span></button>`}).join('');
  document.querySelectorAll('.lesson-button').forEach(button=>button.onclick=()=>{const index=Number(button.dataset.index);if(!isUnlocked(index)){toast('先完成上一关，才能解锁这个节点');return}selectLesson(index,false)});
}

function selectLesson(index,scroll=true){
  if(isRunning){toast('代码正在运行，请稍候');return}
  if(!isUnlocked(index)){toast('该关卡尚未解锁');return}
  selected=index;state.current=index;save();const lesson=currentLesson(),done=state.completed.includes(lesson.id);
  $('previewNumber').textContent=`任务 ${String(index+1).padStart(2,'0')}`;$('previewStatus').textContent=done?'已完成':'可开始';$('previewIcon').innerHTML=lesson.icon;$('previewTitle').textContent=lesson.title;$('previewDescription').textContent=lesson.description;$('previewConcepts').innerHTML=lesson.concepts.map(x=>`<span>${x}</span>`).join('');
  $('labTitle').textContent=lesson.title;$('missionLabel').textContent=`任务 ${String(index+1).padStart(2,'0')}`;$('missionTitle').textContent=lesson.mission;$('missionDescription').textContent=lesson.description;$('knowledgeText').innerHTML=lesson.knowledge;$('checklist').innerHTML=lesson.checklist.map(x=>`<li>${x}</li>`).join('');$('assistBox').classList.remove('show');$('assistBox').innerHTML='';
  $('codeEditor').value=state.code[lesson.id]??lesson.starter;updateLines();clearConsole();$('testSummary').textContent=`0 / ${lesson.checklist.length} 项测试`;$('lessonPosition').textContent=`第 ${index+1} 关 / 共 ${lessons.length} 关`;$('previousLesson').disabled=index===0;$('nextLesson').disabled=index===lessons.length-1||!isUnlocked(index+1);$('answerTitle').textContent=lesson.title;$('answerCode').textContent=lesson.solution;renderNav();
  if(scroll)$('lab').scrollIntoView({behavior:'smooth'});
}

function updateStats(){
  const completed=state.completed.length,percent=Math.round(completed/lessons.length*100),lv=level(),within=state.xp%200;
  $('navLevel').textContent=lv;$('progressLevel').textContent=lv;$('statRuns').textContent=state.runs;$('statLessons').textContent=`${completed} / ${lessons.length}`;$('statXp').textContent=`${state.xp} XP`;$('statPercent').textContent=`${percent}%`;$('progressXp').textContent=`${within} / 200 XP`;$('xpBar').style.width=`${within/2}%`;$('levelRing').style.background=`conic-gradient(var(--cyan) ${within*1.8}deg,#ffffff12 0)`;
  if(completed){$('achievementCard').classList.add('unlocked');$('badgeName').textContent=completed===lessons.length?'Python 小飞侠':'初次启航';$('badgeDescription').textContent=completed===lessons.length?'你已完成 Python 入门航线。':'你已完成第一关并点亮学习信号。'}
}

function initWorker(){
  if(worker)return;worker=new Worker('py-worker.js?v=20260724-2');setRuntime('loading','PYTHON 引擎：正在加载');worker.onmessage=event=>{const job=pending.get(event.data.id);if(!job)return;clearTimeout(job.timer);pending.delete(event.data.id);runtimeLoaded=true;setRuntime('ready','PYTHON 引擎：已就绪');job.resolve(event.data)};worker.onerror=error=>{setRuntime('error','PYTHON 引擎：加载失败');pending.forEach(job=>{clearTimeout(job.timer);job.reject(error)});pending.clear();worker=null;runtimeLoaded=false}
}
function setRuntime(cls,text){const el=$('runtimeStatus');el.className=`runtime ${cls}`;el.querySelector('span').textContent=text}
function execute(code){initWorker();return new Promise((resolve,reject)=>{const id=++requestId;const timer=setTimeout(()=>{pending.delete(id);worker?.terminate();worker=null;runtimeLoaded=false;setRuntime('error','PYTHON 引擎：运行超时');reject(new Error('运行超过 12 秒，请检查是否存在无限循环。'))},12000);pending.set(id,{resolve,reject,timer});worker.postMessage({id,code})})}
function preparedCode(){const lesson=currentLesson();return lesson.input?`import builtins\n_inputs = iter([${JSON.stringify(lesson.input)}])\nbuiltins.input = lambda prompt='': next(_inputs)\n${$('codeEditor').value}`:$('codeEditor').value}

async function run(check){
  if(isRunning)return;const lesson=currentLesson(),lessonIndex=selected,code=$('codeEditor').value;isRunning=true;$('consoleOutput').className='console running';$('consoleOutput').textContent=runtimeLoaded?'> 正在运行 Python...':'> 首次加载 Python 引擎...\n> 请稍候，后续运行会更快。';disableRuns(true);
  try{const result=await execute(preparedCode());state.runs++;save();if(!result.ok){showOutput(result.output,'error');$('testSummary').textContent=`0 / ${lesson.checklist.length} 项测试`;return}showOutput(result.output||'（程序已结束，没有输出内容）','success');if(check){const tests=lesson.test(code,result.output||'');const passed=tests.filter(Boolean).length;$('testSummary').textContent=`${passed} / ${tests.length} 项测试`;if(passed===tests.length)completeLesson(lesson,lessonIndex);else{$('consoleOutput').textContent+=`\n\n检查结果：通过 ${passed}/${tests.length} 项。\n请对照左侧检查项修改后重试。`;$('consoleOutput').className='console error'}}else toast('代码运行成功')
  }catch(error){showOutput('Python 引擎运行失败，请检查网络或代码。\n'+error,'error')}finally{isRunning=false;disableRuns(false)}
}
function disableRuns(value){$('runOnly').disabled=value;$('runTests').disabled=value;$('resetCode').disabled=value;$('previousLesson').disabled=value||selected===0;$('nextLesson').disabled=value||selected===lessons.length-1||!isUnlocked(selected+1)}
function showOutput(text,type){$('consoleOutput').textContent=`> ${text}`;$('consoleOutput').className=`console ${type}`}
function completeLesson(lesson,lessonIndex){const fresh=!state.completed.includes(lesson.id);if(fresh){state.completed.push(lesson.id);state.xp+=lesson.reward;save();toast(`任务完成 // +${lesson.reward} XP`)}else toast('全部测试通过 // 本关已完成');$('consoleOutput').textContent+='\n\n✓ 全部测试通过\n任务完成！';$('consoleOutput').className='console success';renderNav();$('nextLesson').disabled=lessonIndex===lessons.length-1;if(fresh&&lessonIndex<lessons.length-1)setTimeout(()=>toast('下一关已解锁'),1000)}
function clearConsole(){$('consoleOutput').className='console';$('consoleOutput').innerHTML='<span>&gt; 点击“运行并检查”执行真实 Python 代码。</span>'}
function updateLines(){const count=$('codeEditor').value.split('\n').length;$('lineNumbers').textContent=Array.from({length:Math.max(1,count)},(_,i)=>i+1).join('\n')}
function toast(text){const el=$('toast');el.textContent=text;el.classList.add('show');clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.remove('show'),2500)}
function showDialog(show){$('answerDialog').classList.toggle('open',show);$('answerDialog').setAttribute('aria-hidden',String(!show));document.body.style.overflow=show?'hidden':''}

$('openLesson').onclick=()=>selectLesson(selected,true);$('startLearning').onclick=()=>selectLesson(state.current||0,true);$('quickRun').onclick=$('demoRun').onclick=()=>{const out=$('demoOutput');out.textContent='正在运行...';setTimeout(()=>{out.textContent='迪权、得喜、得军、得龙、得女、得得女，准备起飞！';toast('示例运行成功')},500)};$('levelButton').onclick=()=>$('progress').scrollIntoView({behavior:'smooth'});$('runOnly').onclick=()=>run(false);$('runTests').onclick=()=>run(true);$('clearConsole').onclick=clearConsole;
$('showHint').onclick=()=>{const box=$('assistBox');box.innerHTML=`<b>提示 //</b><br>${currentLesson().hint}`;box.classList.toggle('show')};$('showAnswer').onclick=()=>showDialog(true);document.querySelectorAll('[data-close-dialog]').forEach(x=>x.onclick=()=>showDialog(false));$('useAnswer').onclick=()=>{$('codeEditor').value=currentLesson().solution;state.code[currentLesson().id]=$('codeEditor').value;save();updateLines();showDialog(false);toast('参考答案已放入编辑器')};
$('resetCode').onclick=()=>{$('codeEditor').value=currentLesson().starter;state.code[currentLesson().id]=$('codeEditor').value;save();updateLines();toast('代码已重置')};$('codeEditor').addEventListener('input',()=>{state.code[currentLesson().id]=$('codeEditor').value;localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('dirtyState').textContent='正在保存...';clearTimeout($('dirtyState').timer);$('dirtyState').timer=setTimeout(()=>$('dirtyState').textContent='已保存',400);updateLines()});$('previousLesson').onclick=()=>selectLesson(selected-1,true);$('nextLesson').onclick=()=>selectLesson(selected+1,true);
$('resetProgress').onclick=()=>{if(confirm('确定清除所有关卡进度和代码吗？')){state={xp:0,runs:0,completed:[],code:{},current:0};save();selectLesson(0,false);toast('学习进度已重置')}};document.addEventListener('keydown',event=>{if(event.key==='Escape')showDialog(false);if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();run(true)}});

$('messageContent').addEventListener('input',()=>{$('messageCount').textContent=$('messageContent').value.length});
$('messageForm').addEventListener('submit',event=>{event.preventDefault();const name=$('messageName').value.trim(),type=$('messageType').value,title=$('messageTitle').value.trim(),content=$('messageContent').value.trim(),contact=$('messageContact').value.trim();if(!name||!title||!content){toast('请完整填写必填内容');return}const issueTitle=`[${type}] ${title}`;const issueBody=`## 用户留言\n\n- **称呼：** ${name}\n- **类型：** ${type}\n- **联系方式：** ${contact||'未填写'}\n- **提交页面：** ${location.href}\n\n### 留言内容\n\n${content}\n\n---\n由“小菜鸟带你飞”网站留言表单生成。`;const url=`https://github.com/2002chen/python-learning-lab/issues/new?title=${encodeURIComponent(issueTitle)}&body=${encodeURIComponent(issueBody)}&labels=${encodeURIComponent('用户留言')}`;window.open(url,'_blank','noopener');toast('留言内容已生成，请在 GitHub 页面确认提交')});

const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(x=>observer.observe(x));
function stars(){const c=$('stars'),ctx=c.getContext('2d');if(!ctx||matchMedia('(prefers-reduced-motion:reduce)').matches)return;let pts=[];function resize(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);pts=Array.from({length:Math.min(55,Math.floor(innerWidth/22))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.14,vy:(Math.random()-.5)*.14,r:Math.random()*1.2+.4}))}function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);pts.forEach((p,i)=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>innerWidth)p.vx*=-1;if(p.y<0||p.y>innerHeight)p.vy*=-1;ctx.fillStyle=i%4?'#20e9ff70':'#ff4f9e80';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()});requestAnimationFrame(draw)}resize();draw();addEventListener('resize',resize,{passive:true})}stars();updateStats();selectLesson(selected,false);
