(function(){
  const $=id=>document.getElementById(id);let client,session,level='beginner',position=1,question=null,choice=null,checked=false,state={answered:0,correct:0,streak:0};
  subsite.ready.then(async context=>{if(!context)return;client=context.client;session=context.session;await loadCounts();await loadTopics();await loadQuestion()});
  async function loadCounts(){const results=await Promise.all(['beginner','basic','advanced'].map(x=>client.from('questions').select('*',{count:'exact',head:true}).eq('level',x).eq('active',true)));const counts=results.map(x=>x.count||0);$('cloudCount').textContent=counts.reduce((a,b)=>a+b,0);$('bankTotal').textContent=Math.max(3000,counts.reduce((a,b)=>a+b,0));document.querySelectorAll('[data-level]').forEach((button,index)=>{const label=button.querySelector('em');if(label)label.textContent=`${counts[index]} 道`})}
  async function loadTopics(){const {data}=await client.from('questions').select('topic').eq('level',level).eq('active',true).limit(1000);const topics=[...new Set((data||[]).map(x=>x.topic))].sort();$('topicFilter').innerHTML='<option value="">全部知识点</option>'+topics.map(x=>`<option value="${escapeAttr(x)}">${escapeHtml(x)}</option>`).join('')}
  async function loadQuestion(){choice=null;checked=false;$('questionText').textContent='正在从云端获取题目...';$('questionOptions').innerHTML='';$('questionExplanation').classList.remove('show');let query=client.from('questions').select('*').eq('level',level).eq('active',true);const topic=$('topicFilter').value;if(topic)query=query.eq('topic',topic);let {data,error}=await query.order('position').range(position-1,position-1);if((error||!data?.length)&&position>1){position=1;query=client.from('questions').select('*').eq('level',level).eq('active',true);if(topic)query=query.eq('topic',topic);({data,error}=await query.order('position').range(0,0))}question=data?.[0]||null;if(!question){$('questionText').textContent='当前筛选条件下暂时没有题目。';return}render()}
  function render(){$('quizLevelName').textContent=label(level);$('questionNumber').textContent=position;$('questionJump').value=position;$('quizMeter').style.width=`${position/10}%`;$('questionTopic').textContent=question.topic;$('questionText').textContent=question.question_text;$('questionOptions').innerHTML=(question.options||[]).map((x,i)=>`<button data-choice="${i}" class="${choice===i?'selected':''} ${checked&&i===question.correct_index?'correct':''} ${checked&&choice===i&&i!==question.correct_index?'wrong':''}"><i>${String.fromCharCode(65+i)}</i><span>${escapeHtml(x)}</span></button>`).join('');document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{if(checked)return;choice=Number(b.dataset.choice);render()});$('questionExplanation').classList.toggle('show',checked);$('questionExplanation').querySelector('p').textContent=question.explanation;$('submitAnswer').disabled=checked;$('submitAnswer').textContent=checked?'已提交':'提交答案';$('previousQuestion').disabled=position<=1;updateStats()}
  async function submit(){if(choice===null){subsite.toast('请先选择一个答案');return}const correct=choice===question.correct_index;checked=true;state.answered++;if(correct){state.correct++;state.streak++;subsite.toast('回答正确')}else{state.streak=0;subsite.toast('暂未答对，请查看解析')}render();await client.from('quiz_attempts').insert({user_id:session.user.id,question_id:question.id,selected_index:choice,is_correct:correct})}
  function updateStats(){$('answeredCount').textContent=state.answered;$('correctCount').textContent=state.correct;$('streakCount').textContent=state.streak;$('scorePercent').textContent=state.answered?Math.round(state.correct/state.answered*100):0}
  function setLevel(next){level=next;position=1;document.querySelectorAll('[data-level]').forEach(b=>b.classList.toggle('active',b.dataset.level===level));loadTopics().then(loadQuestion)}
  function label(x){return{beginner:'零基础',basic:'基础',advanced:'进阶'}[x]}
  function escapeHtml(x){return String(x).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}function escapeAttr(x){return escapeHtml(x).replace(/"/g,'&quot;')}
  document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>setLevel(b.dataset.level));$('topicFilter').onchange=()=>{position=1;loadQuestion()};$('submitAnswer').onclick=submit;$('nextQuestion').onclick=()=>{if(position<1000){position++;loadQuestion()}};$('previousQuestion').onclick=()=>{if(position>1){position--;loadQuestion()}};$('jumpButton').onclick=()=>{position=Math.min(1000,Math.max(1,Number($('questionJump').value)||1));loadQuestion()};$('randomQuestion').onclick=()=>{position=Math.floor(Math.random()*1000)+1;loadQuestion()};
})();
