-- Run this once in the Supabase SQL Editor for an existing deployment.
-- The full schema file contains the same statements for new deployments.

create table if not exists public.site_announcements (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 80),
  content text not null check (char_length(content) between 1 and 1000),
  published boolean not null default false,
  published_at timestamptz,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists touch_announcements on public.site_announcements;
create trigger touch_announcements before update on public.site_announcements for each row execute function public.touch_updated_at();

alter table public.site_announcements enable row level security;
drop policy if exists "public read published announcements" on public.site_announcements;
drop policy if exists "admins insert announcements" on public.site_announcements;
drop policy if exists "admins update announcements" on public.site_announcements;
drop policy if exists "admins delete announcements" on public.site_announcements;
create policy "public read published announcements" on public.site_announcements for select using (published or public.is_admin());
create policy "admins insert announcements" on public.site_announcements for insert to authenticated with check (public.is_admin());
create policy "admins update announcements" on public.site_announcements for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins delete announcements" on public.site_announcements for delete to authenticated using (public.is_admin());

alter table public.user_messages add column if not exists user_read_at timestamptz;

create or replace function public.mark_message_read(message_id bigint)
returns boolean
language plpgsql security definer set search_path = public as $$
begin
  update public.user_messages
  set user_read_at = coalesce(user_read_at, now())
  where id = message_id and user_id = auth.uid() and admin_reply <> '';
  return found;
end;
$$;
grant execute on function public.mark_message_read(bigint) to authenticated;

-- Site analytics: page visits, unique visitors, trends and admin dashboard data.
create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  visitor_id text not null check (char_length(visitor_id) between 8 and 80),
  user_id uuid references auth.users(id) on delete set null,
  path text not null check (char_length(path) between 1 and 200),
  created_at timestamptz not null default now()
);

alter table public.site_visits enable row level security;
drop policy if exists "visitors insert visits" on public.site_visits;
drop policy if exists "admins read visits" on public.site_visits;
drop policy if exists "admins delete visits" on public.site_visits;
create policy "visitors insert visits" on public.site_visits for insert to anon, authenticated with check (user_id is null or user_id = auth.uid());
create policy "admins read visits" on public.site_visits for select to authenticated using (public.is_admin());
create policy "admins delete visits" on public.site_visits for delete to authenticated using (public.is_admin());

create or replace function public.admin_site_analytics(days integer default 30)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  start_at timestamptz := now() - make_interval(days => greatest(1, least(coalesce(days, 30), 365)));
begin
  if not public.is_admin() then raise exception 'not authorized'; end if;
  return jsonb_build_object(
    'summary', jsonb_build_object(
      'visits', (select count(*) from public.site_visits where created_at >= start_at),
      'unique_visitors', (select count(distinct visitor_id) from public.site_visits where created_at >= start_at),
      'signed_in_visits', (select count(*) from public.site_visits where created_at >= start_at and user_id is not null),
      'registered_users', (select count(*) from public.profiles),
      'messages', (select count(*) from public.user_messages where created_at >= start_at),
      'active_learners', (select count(distinct user_id) from (
        select user_id from public.section_progress where last_read_at >= start_at
        union select user_id from public.exercise_attempts where created_at >= start_at
        union select user_id from public.quiz_attempts where created_at >= start_at
      ) learners)
    ),
    'trend', coalesce((select jsonb_agg(jsonb_build_object('date', day::date, 'visits', visits, 'unique_visitors', unique_visitors) order by day) from (
      select date_trunc('day', created_at) as day, count(*) as visits, count(distinct visitor_id) as unique_visitors
      from public.site_visits where created_at >= start_at group by 1
    ) trend_rows), '[]'::jsonb),
    'top_pages', coalesce((select jsonb_agg(jsonb_build_object('path', path, 'visits', visits) order by visits desc) from (
      select path, count(*) as visits from public.site_visits where created_at >= start_at group by path order by visits desc limit 8
    ) page_rows), '[]'::jsonb),
    'recent', coalesce((select jsonb_agg(jsonb_build_object('path', path, 'created_at', created_at, 'signed_in', user_id is not null) order by created_at desc) from (
      select path, created_at, user_id from public.site_visits order by created_at desc limit 12
    ) recent_rows), '[]'::jsonb)
  );
end;
$$;
grant execute on function public.admin_site_analytics(integer) to authenticated;
