-- Run this file once in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_learning_data (
  user_id uuid primary key references auth.users(id) on delete cascade,
  learning_state jsonb not null default '{}'::jsonb,
  quiz_state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  level text not null check (level in ('beginner', 'basic', 'advanced')),
  topic text not null,
  question_text text not null,
  options jsonb not null check (jsonb_typeof(options) = 'array'),
  correct_index integer not null check (correct_index between 0 and 10),
  explanation text not null default '',
  position integer not null default 0,
  active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.course_chapters (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text not null default '',
  description text not null default '',
  level text not null check (level in ('beginner', 'basic', 'advanced')),
  position integer not null default 0,
  cover_icon text not null default '📘',
  estimated_minutes integer not null default 60,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.course_sections (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references public.course_chapters(id) on delete cascade,
  title text not null,
  summary text not null default '',
  content_html text not null default '',
  example_code text not null default '',
  position integer not null default 0,
  section_type text not null default 'lesson' check (section_type in ('lesson', 'summary')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chapter_exercises (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references public.course_chapters(id) on delete cascade,
  section_id bigint references public.course_sections(id) on delete cascade,
  exercise_group text not null check (exercise_group in ('after_class', 'summary')),
  question_type text not null check (question_type in ('choice', 'short_answer', 'coding', 'thinking')),
  topic text not null default '',
  prompt text not null,
  options jsonb not null default '[]'::jsonb,
  correct_answer text not null default '',
  correct_index integer,
  explanation text not null default '',
  starter_code text not null default '',
  test_config jsonb not null default '{}'::jsonb,
  position integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.section_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  section_id bigint not null references public.course_sections(id) on delete cascade,
  completed boolean not null default false,
  last_read_at timestamptz not null default now(),
  primary key (user_id, section_id)
);

create table if not exists public.exercise_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  exercise_id bigint not null references public.chapter_exercises(id) on delete cascade,
  answer_text text not null default '',
  selected_index integer,
  is_correct boolean,
  score numeric(5,2) not null default 0,
  feedback text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  selected_index integer not null,
  is_correct boolean not null,
  created_at timestamptz not null default now()
);

create index if not exists quiz_attempts_user_idx on public.quiz_attempts(user_id, created_at desc);
create index if not exists questions_level_idx on public.questions(level, active, position);
create index if not exists course_sections_chapter_idx on public.course_sections(chapter_id, position);
create index if not exists chapter_exercises_chapter_idx on public.chapter_exercises(chapter_id, exercise_group, question_type, position);
create index if not exists exercise_attempts_user_idx on public.exercise_attempts(user_id, created_at desc);
create unique index if not exists course_chapters_title_idx on public.course_chapters(title);
create unique index if not exists course_sections_title_idx on public.course_sections(chapter_id, title);
create unique index if not exists chapter_exercises_position_idx on public.chapter_exercises(chapter_id, exercise_group, question_type, position);

create table if not exists public.user_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  sender_name text not null,
  message_type text not null,
  title text not null,
  content text not null,
  contact text not null default '',
  status text not null default 'new' check (status in ('new', 'processing', 'resolved')),
  admin_reply text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  insert into public.user_learning_data(user_id) values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists touch_profiles on public.profiles;
create trigger touch_profiles before update on public.profiles for each row execute function public.touch_updated_at();
drop trigger if exists touch_learning on public.user_learning_data;
create trigger touch_learning before update on public.user_learning_data for each row execute function public.touch_updated_at();
drop trigger if exists touch_questions on public.questions;
create trigger touch_questions before update on public.questions for each row execute function public.touch_updated_at();
drop trigger if exists touch_messages on public.user_messages;
create trigger touch_messages before update on public.user_messages for each row execute function public.touch_updated_at();
drop trigger if exists touch_course_chapters on public.course_chapters;
create trigger touch_course_chapters before update on public.course_chapters for each row execute function public.touch_updated_at();
drop trigger if exists touch_course_sections on public.course_sections;
create trigger touch_course_sections before update on public.course_sections for each row execute function public.touch_updated_at();
drop trigger if exists touch_chapter_exercises on public.chapter_exercises;
create trigger touch_chapter_exercises before update on public.chapter_exercises for each row execute function public.touch_updated_at();

alter table public.profiles enable row level security;
alter table public.user_learning_data enable row level security;
alter table public.questions enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.user_messages enable row level security;
alter table public.course_chapters enable row level security;
alter table public.course_sections enable row level security;
alter table public.chapter_exercises enable row level security;
alter table public.section_progress enable row level security;
alter table public.exercise_attempts enable row level security;

drop policy if exists "profiles self read" on public.profiles;
create policy "profiles self read" on public.profiles for select using (id = auth.uid() or public.is_admin());

drop policy if exists "learning self read" on public.user_learning_data;
drop policy if exists "learning self insert" on public.user_learning_data;
drop policy if exists "learning self update" on public.user_learning_data;
drop policy if exists "learning self delete" on public.user_learning_data;
create policy "learning self read" on public.user_learning_data for select using (user_id = auth.uid());
create policy "learning self insert" on public.user_learning_data for insert with check (user_id = auth.uid());
create policy "learning self update" on public.user_learning_data for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "learning self delete" on public.user_learning_data for delete using (user_id = auth.uid());

drop policy if exists "authenticated read active questions" on public.questions;
drop policy if exists "admins insert questions" on public.questions;
drop policy if exists "admins update questions" on public.questions;
drop policy if exists "admins delete questions" on public.questions;
create policy "authenticated read active questions" on public.questions for select to authenticated using (active or public.is_admin());
create policy "admins insert questions" on public.questions for insert to authenticated with check (public.is_admin());
create policy "admins update questions" on public.questions for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins delete questions" on public.questions for delete to authenticated using (public.is_admin());

drop policy if exists "attempts self read" on public.quiz_attempts;
drop policy if exists "attempts self insert" on public.quiz_attempts;
create policy "attempts self read" on public.quiz_attempts for select using (user_id = auth.uid() or public.is_admin());
create policy "attempts self insert" on public.quiz_attempts for insert with check (user_id = auth.uid());

drop policy if exists "messages self read" on public.user_messages;
drop policy if exists "messages self insert" on public.user_messages;
drop policy if exists "admins update messages" on public.user_messages;
drop policy if exists "messages self delete" on public.user_messages;
create policy "messages self read" on public.user_messages for select using (user_id = auth.uid() or public.is_admin());
create policy "messages self insert" on public.user_messages for insert with check (user_id = auth.uid());
create policy "admins update messages" on public.user_messages for update using (public.is_admin()) with check (public.is_admin());
create policy "messages self delete" on public.user_messages for delete using (user_id = auth.uid() or public.is_admin());

drop policy if exists "authenticated read chapters" on public.course_chapters;
drop policy if exists "admins manage chapters insert" on public.course_chapters;
drop policy if exists "admins manage chapters update" on public.course_chapters;
drop policy if exists "admins manage chapters delete" on public.course_chapters;
create policy "authenticated read chapters" on public.course_chapters for select to authenticated using (active or public.is_admin());
create policy "admins manage chapters insert" on public.course_chapters for insert to authenticated with check (public.is_admin());
create policy "admins manage chapters update" on public.course_chapters for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins manage chapters delete" on public.course_chapters for delete to authenticated using (public.is_admin());

drop policy if exists "authenticated read sections" on public.course_sections;
drop policy if exists "admins manage sections insert" on public.course_sections;
drop policy if exists "admins manage sections update" on public.course_sections;
drop policy if exists "admins manage sections delete" on public.course_sections;
create policy "authenticated read sections" on public.course_sections for select to authenticated using (active or public.is_admin());
create policy "admins manage sections insert" on public.course_sections for insert to authenticated with check (public.is_admin());
create policy "admins manage sections update" on public.course_sections for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins manage sections delete" on public.course_sections for delete to authenticated using (public.is_admin());

drop policy if exists "authenticated read exercises" on public.chapter_exercises;
drop policy if exists "admins manage exercises insert" on public.chapter_exercises;
drop policy if exists "admins manage exercises update" on public.chapter_exercises;
drop policy if exists "admins manage exercises delete" on public.chapter_exercises;
create policy "authenticated read exercises" on public.chapter_exercises for select to authenticated using (active or public.is_admin());
create policy "admins manage exercises insert" on public.chapter_exercises for insert to authenticated with check (public.is_admin());
create policy "admins manage exercises update" on public.chapter_exercises for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins manage exercises delete" on public.chapter_exercises for delete to authenticated using (public.is_admin());

drop policy if exists "section progress self read" on public.section_progress;
drop policy if exists "section progress self insert" on public.section_progress;
drop policy if exists "section progress self update" on public.section_progress;
create policy "section progress self read" on public.section_progress for select using (user_id = auth.uid());
create policy "section progress self insert" on public.section_progress for insert with check (user_id = auth.uid());
create policy "section progress self update" on public.section_progress for update using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "exercise attempts self read" on public.exercise_attempts;
drop policy if exists "exercise attempts self insert" on public.exercise_attempts;
create policy "exercise attempts self read" on public.exercise_attempts for select using (user_id = auth.uid() or public.is_admin());
create policy "exercise attempts self insert" on public.exercise_attempts for insert with check (user_id = auth.uid());

-- After your first account is registered, make it administrator once:
-- update public.profiles set role = 'admin' where id = 'YOUR_USER_UUID';
