-- Run this once in the Supabase SQL Editor for an existing deployment.
-- The full schema file contains the same statements for new deployments.

create table if not exists public.site_announcements (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 80),
  content text not null check (char_length(content) between 1 and 1000),
  published boolean not null default false,
  published_at timestamptz,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists touch_announcements on public.site_announcements;
create trigger touch_announcements before update on public.site_announcements for each row execute function public.touch_updated_at();

alter table public.site_announcements enable row level security;
drop policy if exists "public read published announcements" on public.site_announcements;
drop policy if exists "admins insert announcements" on public.site_announcements;
drop policy if exists "admins update announcements" on public.site_announcements;
drop policy if exists "admins delete announcements" on public.site_announcements;
create policy "public read published announcements" on public.site_announcements for select using (published or public.is_admin());
create policy "admins insert announcements" on public.site_announcements for insert to authenticated with check (public.is_admin());
create policy "admins update announcements" on public.site_announcements for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins delete announcements" on public.site_announcements for delete to authenticated using (public.is_admin());
