(function(){
  const $=id=>document.getElementById(id);let client,session,chapters=[],sections=[],progress=new Set(),chapter,section,fontStep=0;
  subsite.ready.then(async context=>{if(!context)return;client=context.client;session=context.session;await load()});
  async function load(){const [a,b,c]=await Promise.all([client.from('course_chapters').select('*').eq('active',true).order('position'),client.from('course_sections').select('*').eq('active',true).order('position'),client.from('section_progress').select('section_id,completed').eq('completed',true)]);if(a.error||b.error){$('chapterList').innerHTML='<div class="empty">课程加载失败，请稍后刷新。</div>';return}chapters=a.data||[];sections=b.data||[];progress=new Set((c.data||[]).map(x=>x.section_id));renderCatalog();updateProgress();const requested=Number(new URLSearchParams(location.search).get('section'));const first=sections.find(x=>x.id===requested)||sections[0];if(first)selectSection(first.id)}
  function renderCatalog(){ $('chapterList').innerHTML=chapters.map((c,index)=>{const list=sections.filter(s=>s.chapter_id===c.id),done=list.filter(s=>progress.has(s.id)).length;return `<div class="chapter-group ${chapter?.id===c.id?'open':''}"><button class="chapter-button" data-chapter="${c.id}"><i>${c.cover_icon}</i><span><small>第 ${index+1} 章 · ${level(c.level)}</small><b>${c.title}</b></span><em>${done}/${list.length}</em></button><div class="section-list">${list.map(s=>`<button class="section-button ${s.id===section?.id?'active':''} ${progress.has(s.id)?'done':''}" data-section="${s.id}">${s.title}</button>`).join('')}</div></div>`}).join('');document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>{chapter=chapters.find(x=>x.id===Number(b.dataset.chapter));renderCatalog()});document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>selectSection(Number(b.dataset.section)))}
  function selectSection(id){section=sections.find(x=>x.id===id);if(!section)return;chapter=chapters.find(x=>x.id===section.chapter_id);renderCatalog();$('readerEmpty').style.display='none';$('readerContent').classList.add('show');$('readerBreadcrumb').textContent=`第 ${chapters.indexOf(chapter)+1} 章 / ${chapter.title}`;$('readerType').textContent=section.section_type==='summary'?'章节小结':'教程小节';$('readerTitle').textContent=section.title;$('readerSummary').textContent=section.summary;$('readerReadTime').textContent=`约 ${Math.max(5,Math.ceil((section.content_html||'').length/420))} 分钟 · 零基础友好`;$('readerStatus').textContent=progress.has(id)?'已完成':'未完成';$('tutorialBody').innerHTML=section.content_html;$('tutorialCode').textContent=section.example_code||'';$('tutorialCodeBox').style.display=section.example_code?'block':'none';$('completeSection').textContent=progress.has(id)?'本节已完成 ✓':'标记本节已学完 ✓';const list=sections.filter(x=>x.chapter_id===chapter.id),pos=list.findIndex(x=>x.id===id);$('readerPrevious').disabled=pos===0;$('readerNext').disabled=pos===list.length-1;$('readerPrevious').onclick=()=>pos>0&&selectSection(list[pos-1].id);$('readerNext').onclick=()=>pos<list.length-1&&selectSection(list[pos+1].id);$('chapterQuizLink').href=`quiz.html?chapter=${chapter.id}`;history.replaceState(null,'',`?section=${id}`);scrollTo({top:0,behavior:'smooth'})}
  async function complete(){if(!section)return;const {error}=await client.from('section_progress').upsert({user_id:session.user.id,section_id:section.id,completed:true,last_read_at:new Date().toISOString()});if(error){subsite.toast('进度保存失败');return}progress.add(section.id);renderCatalog();selectSection(section.id);updateProgress();subsite.toast('本节已完成，学习进度已同步')}
  function updateProgress(){const percent=sections.length?Math.round(progress.size/sections.length*100):0;$('courseProgressText').textContent=`${percent}%`;$('courseProgressBar').style.width=`${percent}%`;$('heroProgressBar').style.width=`${percent}%`;$('heroProgressText').textContent=`已完成 ${progress.size} / ${sections.length} 个小节`}
  function level(x){return{beginner:'零基础',basic:'基础',advanced:'进阶'}[x]||x}
  $('completeSection').onclick=complete;$('copyTutorialCode').onclick=()=>navigator.clipboard.writeText($('tutorialCode').textContent).then(()=>subsite.toast('代码已复制'));document.querySelectorAll('[data-font]').forEach(b=>b.onclick=()=>{fontStep=Number(b.dataset.font);$('tutorialBody').style.setProperty('--reader-size',`${18+fontStep*2}px`);subsite.toast(fontStep===0?'已恢复标准字号':fontStep>0?'已放大正文字号':'已缩小正文字号')});$('collapseCatalog').onclick=()=>{$('chapterList').closest('.tutorial-catalog').classList.toggle('collapsed');$('collapseCatalog').textContent=$('chapterList').closest('.tutorial-catalog').classList.contains('collapsed')?'展开':'收起'};
})();
