(function () {
  'use strict';

  const chapters = [
    ['从第一行代码起飞', '先理解运行，再学习语法', 'beginner', 35],
    ['变量与简单数据', '让程序记住文字和数字', 'beginner', 55],
    ['列表：管理一组数据', '从一条清单开始', 'beginner', 60],
    ['遍历列表与数据整理', '让一段代码处理整组数据', 'beginner', 65],
    ['条件判断', '让程序根据情况做选择', 'basic', 65],
    ['字典：描述一条完整记录', '用键和值组织信息', 'basic', 65],
    ['输入与 while 循环', '让程序和用户持续对话', 'basic', 70],
    ['函数', '把可靠步骤封装成工具', 'basic', 80],
    ['类与对象', '为数据和行为建立模型', 'advanced', 85],
    ['文件、异常与测试', '保存结果并验证程序', 'advanced', 90],
    ['项目实践：文字冒险', '把基础知识连接成程序', 'advanced', 100],
    ['数据、接口与 Web 入门', '认识真实项目的三条方向', 'advanced', 110]
  ].map((item, index) => ({
    id: `original-chapter-${index + 1}`,
    position: index + 1,
    title: item[0],
    subtitle: item[1],
    description: item[1],
    level: item[2],
    cover_icon: String(index + 1).padStart(2, '0'),
    estimated_minutes: item[3]
  }));

  const rawLessons = [
    [1, 1, '代码、运行与输出', '弄清楚写代码和运行代码的区别。',
      '<h3>代码不会自己动起来</h3><p>代码是写给电脑的操作说明。编辑器负责保存说明，运行按钮把说明交给 Python 执行，输出区展示执行结果。这三个区域分工不同。</p><h3>先观察，再修改</h3><p><code>print()</code> 会把括号里的内容显示出来。引号表示其中是文字，括号表示交给 print 的内容。先运行原代码，再只改引号里的中文，你会更容易看清“改动”和“结果”的关系。</p><div class="checkpoint"><b>本节目标</b><p>能用自己的话解释代码、运行和输出，并成功修改一行文字。</p></div>',
      'print("你好，Python")\nprint("今天从第一行开始")',
      '为什么代码写在编辑器里后，还要点击运行才会出现结果？',
      '把第二行改成你的学习宣言，并运行两行代码。', '你好，Python\n我会每天练习', 'print('],
    [1, 2, '变量：给信息起名字', '用有意义的名字保存数据。',
      '<h3>变量不是盒子，更像标签</h3><p><code>name = "小林"</code> 让名字 <code>name</code> 指向一段文字。之后程序可以通过变量名再次使用这个值，也可以让同一个名字指向新值。</p><h3>名字要帮助阅读</h3><p><code>student_age</code> 比 <code>a</code> 更容易理解。变量名可以包含字母、数字和下划线，但不能以数字开头，也不能使用 Python 关键字。</p><div class="tip">赋值从右向左理解：先得到右侧的值，再把它交给左侧的变量名。</div>',
      'learner = "小林"\ncourse = "Python 入门"\nprint(learner, "正在学习", course)',
      '为什么 student_name 通常比 n 更适合保存学生姓名？',
      '创建 city 和 goal 两个变量，输出“我在成都，目标是写出第一个程序”。', '我在成都，目标是写出第一个程序', 'city ='],
    [1, 3, '错误是线索，不是失败', '学会阅读最常见的语法错误。',
      '<h3>调试是一种工作方法</h3><p>程序报错时，先看错误的最后一行，再看它指出的行号。初学阶段最常见的是拼写错误、符号不成对和缩进不一致。</p><h3>一次只改一个地方</h3><p>同时修改很多行，会让你不知道是哪项改动解决了问题。更可靠的顺序是：复现问题、缩小范围、修改一处、重新运行。</p><div class="checkpoint"><b>形成习惯</b><p>保留能够工作的部分，只针对报错附近做小改动。</p></div>',
      'message = "报错会告诉我从哪里检查"\nprint(message)',
      '为什么修复错误时“一次只改一个地方”更容易找到原因？',
      '修复 starter code 中缺少的右括号，让程序输出“调试完成”。', '调试完成', 'print('],

    [2, 1, '字符串与文本方法', '整理大小写、空白和多段文字。',
      '<h3>字符串就是文本</h3><p>单引号和双引号都能创建字符串，只要前后成对。方法 <code>strip()</code> 可以去掉两端空白，<code>title()</code>、<code>upper()</code> 和 <code>lower()</code> 可以生成不同大小写的新字符串。</p><h3>原值不会自动改变</h3><p>字符串不能原地修改。调用方法会返回新字符串，需要赋值给变量才能长期保存。</p>',
      'raw_name = "  xiao lin  "\nclean_name = raw_name.strip().title()\nprint(clean_name)',
      '为什么 raw_name.strip() 不会自动永久改变 raw_name？',
      '清理文本“  python learner  ”两侧空格并转成标题格式后输出。', 'Python Learner', '.strip()'],
    [2, 2, '数字与运算顺序', '使用整数、小数和括号完成计算。',
      '<h3>数字也有类型</h3><p>没有小数部分的数通常是 <code>int</code>，带小数点的数通常是 <code>float</code>。加减乘除使用 <code>+ - * /</code>，<code>**</code> 表示乘方，<code>%</code> 表示余数。</p><h3>用括号表达意图</h3><p>Python 遵循运算优先级。即使默认顺序正好符合预期，适当的括号也能让读者更快看懂。</p>',
      'price = 12.5\ncount = 4\ndiscount = 6\ntotal = price * count - discount\nprint(total)',
      '20 + 5 * 2 与 (20 + 5) * 2 为什么不同？',
      '单价 18 元买 3 件，优惠 4 元，计算并输出 50。', '50', '*'],
    [2, 3, '格式化输出与类型转换', '把数据组织成可读的句子。',
      '<h3>f-string 负责组织结果</h3><p>在字符串前写 <code>f</code>，便可以把变量或简单表达式放进花括号。这样比不断使用加号拼接更清楚。</p><h3>文字数字不能直接计算</h3><p><code>"18"</code> 是文本，<code>18</code> 是整数。确认格式可靠后，可用 <code>int()</code> 或 <code>float()</code> 转换。</p>',
      'age_text = "18"\nage = int(age_text)\nprint(f"明年 {age + 1} 岁")',
      '为什么程序不能直接计算 "18" + 1？',
      '将字符串“120”转成整数，加上 30，输出“累计 150 XP”。', '累计 150 XP', 'int('],

    [3, 1, '创建、读取和修改列表', '用索引管理有顺序的数据。',
      '<h3>列表保存一组值</h3><p>方括号创建列表，元素之间用逗号分隔。索引从 0 开始，因此第一项是 <code>items[0]</code>，最后一项可以写成 <code>items[-1]</code>。</p><h3>列表可以修改</h3><p>可以通过索引替换元素，也可以用 <code>append()</code> 在末尾添加，用 <code>insert()</code> 在指定位置插入。</p>',
      'tasks = ["读教程", "运行示例"]\ntasks.append("完成作业")\ntasks[0] = "复习教程"\nprint(tasks)',
      '为什么列表第一项的索引是 0，而不是 1？',
      '创建包含“变量、列表”的列表，再追加“循环”并输出。', "['变量', '列表', '循环']", '.append('],
    [3, 2, '删除、排序与长度', '维护一份会变化的清单。',
      '<h3>按目标选择删除方式</h3><p>知道位置时可以用 <code>pop()</code>，知道值时可以用 <code>remove()</code>。<code>pop()</code> 还会返回被删除的元素。</p><h3>排序是否要保留原顺序</h3><p><code>sorted()</code> 返回新列表，<code>sort()</code> 会修改原列表。<code>len()</code> 返回元素数量。</p>',
      'scores = [88, 95, 72]\nordered = sorted(scores, reverse=True)\nprint(ordered)\nprint(len(scores))',
      'sorted(scores) 和 scores.sort() 的主要区别是什么？',
      '将 [3, 1, 2] 从小到大排序，不修改原列表，并输出排序结果。', '[1, 2, 3]', 'sorted('],
    [3, 3, '切片与复制', '取得列表的一部分并避免意外共享。',
      '<h3>切片包含开头，不包含结尾</h3><p><code>items[1:4]</code> 取得索引 1、2、3 对应的元素。省略开头或结尾，可以方便地取得前几项或后几项。</p><h3>复制不是多起一个名字</h3><p><code>backup = items</code> 让两个变量指向同一列表；<code>backup = items[:]</code> 才会创建浅复制。</p>',
      'topics = ["变量", "列表", "循环", "函数"]\nfirst_two = topics[:2]\nbackup = topics[:]\nprint(first_two)\nprint(len(backup))',
      '为什么 backup = items 后，修改 backup 也可能影响 items？',
      '从 [10, 20, 30, 40] 中切出中间两项并输出。', '[20, 30]', '[1:3]'],

    [4, 1, 'for 循环遍历列表', '对每一个元素执行相同操作。',
      '<h3>循环让重复意图更清楚</h3><p><code>for name in names</code> 会依次把列表元素交给变量 name。缩进的代码属于循环体，每个元素都会执行一次。</p><h3>变量名要说明当前元素</h3><p>遍历 <code>students</code> 时使用 <code>student</code>，通常比 <code>x</code> 更易读。</p>',
      'learners = ["小林", "阿禾", "小周"]\nfor learner in learners:\n    print(f"{learner}，继续加油")',
      'for learner in learners 中，learner 每一轮分别代表什么？',
      '遍历 ["变量", "列表", "循环"]，逐行输出“已学习：知识点”。', '已学习：变量\n已学习：列表\n已学习：循环', 'for '],
    [4, 2, 'range、累加与列表推导式', '生成数字序列并汇总结果。',
      '<h3>range 的结束值不包含</h3><p><code>range(1, 5)</code> 产生 1 到 4。这个规则便于表达“从起点开始，共处理若干项”。</p><h3>先写普通循环</h3><p>列表推导式适合简短的转换。逻辑复杂时，普通 for 循环更容易调试，不必为了简短而压缩代码。</p>',
      'total = 0\nfor number in range(1, 6):\n    total += number\nsquares = [n ** 2 for n in range(1, 4)]\nprint(total)\nprint(squares)',
      'range(1, 5) 为什么不会产生 5？',
      '使用循环计算 1 到 10 的总和并输出。', '55', 'range('],
    [4, 3, '元组与固定数据', '区分需要修改和不应修改的数据。',
      '<h3>元组表达固定结构</h3><p>元组用圆括号表示，创建后不能替换其中元素。坐标、颜色通道、固定配置等数据适合用元组表达。</p><h3>不能修改，不代表永远不能重建</h3><p>变量仍然可以指向一个新元组。关键是原来的元组对象不会被原地修改。</p>',
      'screen_size = (1280, 720)\nwidth, height = screen_size\nprint(width)\nprint(height)',
      '地图坐标为什么通常比购物清单更适合使用元组？',
      '创建 RGB 元组 (176, 92, 55)，解包后逐行输出三个值。', '176\n92\n55', '= ('],

    [5, 1, '布尔表达式与比较', '把现实规则写成 True 或 False。',
      '<h3>比较会产生布尔值</h3><p><code>==</code> 判断相等，<code>!=</code> 判断不等，此外还有大于、小于等比较。单等号用于赋值，双等号用于比较。</p><h3>先给复杂条件起名字</h3><p>把复杂判断拆成 <code>is_adult</code>、<code>has_ticket</code> 等变量，可以让后续条件更像自然语言。</p>',
      'age = 20\nis_adult = age >= 18\nhas_ticket = True\nprint(is_adult and has_ticket)',
      '= 和 == 分别做什么？混用后会造成什么问题？',
      '设置 score = 86，输出 score 是否大于等于 60。', 'True', '>='],
    [5, 2, 'if、elif 与 else', '按顺序选择一个分支执行。',
      '<h3>分支按从上到下检查</h3><p>条件成立后，Python 执行对应代码块，并跳过同组后续分支。因此区间判断通常从更严格的条件开始。</p><h3>缩进决定代码归属</h3><p>Python 使用缩进表示代码块。建议始终使用 4 个空格，避免混用 Tab。</p>',
      'score = 86\nif score >= 90:\n    print("优秀")\nelif score >= 75:\n    print("良好")\nelse:\n    print("继续练习")',
      '成绩区间判断为什么通常先检查 90 分，再检查 60 分？',
      '根据 temperature = 31 输出“炎热”：30 以上炎热，20 以上舒适，否则偏冷。', '炎热', 'elif '],
    [5, 3, '组合条件与列表判断', '使用 and、or、not 描述规则。',
      '<h3>组合多个事实</h3><p><code>and</code> 要求两边都成立，<code>or</code> 只要求至少一边成立，<code>not</code> 反转真假。括号可以明确组合顺序。</p><h3>检查成员是否存在</h3><p><code>item in items</code> 判断元素是否存在，<code>not in</code> 判断不存在。</p>',
      'role = "editor"\nis_active = True\nif role in ["admin", "editor"] and is_active:\n    print("允许进入后台")',
      '“已登录，并且是管理员或编辑”应该如何分组条件？',
      '当 user = "小林" 存在于 allowed 列表且未被禁用时，输出“允许访问”。', '允许访问', ' and '],

    [6, 1, '创建和读取字典', '用键值对描述一条记录。',
      '<h3>键让数据自带说明</h3><p>列表按位置读取，字典按键读取。学生记录可以包含 name、score、level 等键，比记住每个位置的含义更可靠。</p><h3>安全读取未知键</h3><p>方括号读取不存在的键会报错；<code>get()</code> 可以提供默认值。</p>',
      'learner = {"name": "小林", "xp": 120}\nprint(learner["name"])\nprint(learner.get("level", "新手"))',
      '学生档案为什么通常比单纯列表更适合使用字典？',
      '创建包含 title 和 minutes 的课程字典，输出课程标题。', 'Python 入门', '["title"]'],
    [6, 2, '修改、删除与遍历字典', '维护持续变化的结构化数据。',
      '<h3>字典可以持续更新</h3><p>为新键赋值可以新增字段，为已有键赋值可以更新字段。<code>del</code> 删除确定存在的键，<code>pop()</code> 删除并返回值。</p><h3>遍历键和值</h3><p><code>items()</code> 同时提供键和值，<code>keys()</code> 和 <code>values()</code> 分别遍历其中一部分。</p>',
      'progress = {"chapter": 2, "xp": 80}\nprogress["xp"] += 20\nprogress["streak"] = 3\nfor key, value in progress.items():\n    print(key, value)',
      '遍历字典时，什么情况下需要 items()，什么情况下只需要 keys()？',
      '将 profile 中的 xp 从 90 增加到 100，并输出。', '100', '["xp"]'],
    [6, 3, '字典与列表嵌套', '组织多条复杂记录。',
      '<h3>容器可以组合</h3><p>“多个学生”可以表示为字典列表；“按班级保存学生”可以表示为值为列表的字典。结构应贴近数据要表达的关系。</p><h3>逐层拆开读取</h3><p>嵌套过深会难以阅读。先把中间结果保存到变量，再继续处理，通常更容易调试。</p>',
      'learners = [\n    {"name": "小林", "xp": 120},\n    {"name": "阿禾", "xp": 95}\n]\nfor learner in learners:\n    print(learner["name"], learner["xp"])',
      '如果要保存三名学生各自的姓名和分数，你会怎样组合列表和字典？',
      '遍历给定的商品字典列表，逐行输出商品名。', '书\n笔', 'for '],

    [7, 1, 'input 与用户输入', '接收文字并给出反馈。',
      '<h3>input 返回字符串</h3><p><code>input()</code> 会暂停程序等待用户输入，得到的结果始终是字符串。需要计算时再进行类型转换。</p><h3>提示语也是界面</h3><p>清楚的提示要告诉用户应该输入什么格式，错误反馈要说明如何改正。</p>',
      'name = "小林"  # 在线示例用固定值模拟输入\nprint(f"你好，{name}")',
      '为什么用户输入 18 后，程序得到的仍然是字符串？',
      '用变量模拟用户输入的城市，并输出“欢迎来到成都”。', '欢迎来到成都', 'city ='],
    [7, 2, 'while 与停止条件', '在条件成立时持续工作。',
      '<h3>while 适合次数未知的重复</h3><p>每轮开始前都会检查条件。循环体必须让条件有机会变为 False，否则程序可能永远停不下来。</p><h3>设计循环的三个问题</h3><p>初始状态是什么？继续条件是什么？每一轮怎样更新状态？写代码前先回答这三个问题。</p>',
      'count = 3\nwhile count > 0:\n    print(count)\n    count -= 1\nprint("开始")',
      '检查 while 循环是否会停止时，应该重点看哪三个部分？',
      '使用 while 从 1 输出到 4。', '1\n2\n3\n4', 'while '],
    [7, 3, 'break、标志与输入校验', '控制交互循环何时结束。',
      '<h3>两种清楚的退出方式</h3><p><code>break</code> 适合遇到明确退出指令时立即结束。布尔标志适合多个位置都可能改变程序状态的情况。</p><h3>先验证，再转换</h3><p>不要假设所有输入都正确。可以检查字符串格式，或使用异常处理给出友好反馈。</p>',
      'commands = ["学习", "练习", "退出", "不会执行"]\nfor command in commands:\n    if command == "退出":\n        break\n    print(command)',
      '什么情况下使用 break 比使用布尔标志更直观？',
      '遍历给定命令，遇到 stop 时结束，只输出 stop 之前的内容。', 'run\ncheck', 'break'],

    [8, 1, '定义与调用函数', '为一项明确任务命名。',
      '<h3>函数是一段有名字的步骤</h3><p><code>def</code> 定义函数，缩进部分是函数体。函数定义后不会自动执行，需要通过函数名加括号调用。</p><h3>函数应该职责明确</h3><p>一个函数只完成一件主要事情，更容易复用、测试和修改。</p>',
      'def build_greeting():\n    return "你好，Python 学习者"\n\nmessage = build_greeting()\nprint(message)',
      '为什么函数定义完成后，函数体不会立刻执行？',
      '定义 show_goal()，返回“完成第一章”，再打印调用结果。', '完成第一章', 'def '],
    [8, 2, '参数、实参与默认值', '让同一个函数处理不同数据。',
      '<h3>参数是函数的输入接口</h3><p>定义函数时写的是形参，调用时传入的是实参。关键字实参能明确每个值的用途，默认值适合最常见的情况。</p><h3>默认参数放在后面</h3><p>没有默认值的参数应位于有默认值参数之前，避免调用规则含糊。</p>',
      'def course_label(name, level="入门"):\n    return f"{name} · {level}"\n\nprint(course_label("Python"))\nprint(course_label("数据分析", level="进阶"))',
      '位置实参与关键字实参各有什么优点？',
      '定义 total(price, count=1)，用关键字实参计算 12.5×4。', '50.0', 'count=1'],
    [8, 3, '返回值、模块与职责', '组合多个小函数完成任务。',
      '<h3>return 把结果交回调用方</h3><p><code>print()</code> 负责展示，<code>return</code> 负责把值交给后续代码。返回值可以保存、计算或传给另一个函数。</p><h3>模块组织相关工具</h3><p>模块是 Python 文件。标准库已经提供许多可靠工具，导入需要的模块比重复实现更合适。</p>',
      'import math\n\ndef circle_area(radius):\n    return math.pi * radius ** 2\n\narea = circle_area(2)\nprint(round(area, 2))',
      '函数内部直接 print 结果，与 return 结果有什么区别？',
      '定义 double(n) 返回两倍结果，再用它计算并输出 14。', '14', 'return'],

    [9, 1, '类、对象、属性与方法', '把相关数据和行为放在一起。',
      '<h3>类描述共同结构</h3><p>类像一份模型，说明一类对象拥有哪些数据和行为。对象是根据类创建的具体实例。</p><h3>方法是属于对象的函数</h3><p>实例方法第一个参数通常写作 <code>self</code>，它代表当前对象。</p>',
      'class Learner:\n    def study(self):\n        return "正在学习"\n\nlearner = Learner()\nprint(learner.study())',
      '“学生”这个类和“小林这名学生”这个对象有什么区别？',
      '定义 Book 类和 read 方法，让对象输出“开始阅读”。', '开始阅读', 'class Book'],
    [9, 2, '__init__ 与实例数据', '创建对象时保存各自的数据。',
      '<h3>初始化每个对象</h3><p>创建对象时，Python 会调用 <code>__init__</code>。把参数保存到 <code>self.name</code> 等属性后，每个对象就能拥有不同数据。</p><h3>方法可以更新状态</h3><p>对象的方法不仅能读取属性，也可以以受控方式修改属性。</p>',
      'class Learner:\n    def __init__(self, name, xp=0):\n        self.name = name\n        self.xp = xp\n\n    def earn(self, amount):\n        self.xp += amount\n\nlearner = Learner("小林", 90)\nlearner.earn(10)\nprint(learner.xp)',
      '两个 Learner 对象为什么可以拥有不同的 name 和 xp？',
      '定义 Product，初始化 name 和 price，创建对象后输出“书：39”。', '书：39', '__init__'],
    [9, 3, '继承与组合', '复用能力，同时保持职责清楚。',
      '<h3>继承表达“是一种”</h3><p>子类可以复用父类方法，也可以重写行为。只有当两者确实存在稳定的类型关系时，继承才自然。</p><h3>组合表达“拥有一个”</h3><p>学习平台拥有通知服务，更适合组合；通知服务并不是一种学习平台。组合通常让部件替换更容易。</p>',
      'class Learner:\n    def study(self):\n        return "学习中"\n\nclass PythonLearner(Learner):\n    def study(self):\n        return "正在练习 Python"\n\nprint(PythonLearner().study())',
      '“是一种”和“拥有一个”分别对应继承与组合中的哪一种关系？',
      '让 Cat 继承 Animal 并重写 speak，输出“喵”。', '喵', 'class Cat'],

    [10, 1, '读取与写入文件', '把程序结果保存到下一次运行。',
      '<h3>使用 with 管理文件</h3><p><code>with</code> 代码块结束后会自动关闭文件。读取用 r，覆盖写入用 w，追加用 a；中文文本通常明确指定 UTF-8。</p><h3>确认覆盖是否符合意图</h3><p>w 模式会清空原内容。写入前要判断是替换整份文件，还是追加一条记录。</p>',
      'with open("note.txt", "w", encoding="utf-8") as file:\n    file.write("今天完成一节教程")\n\nwith open("note.txt", encoding="utf-8") as file:\n    print(file.read())',
      'w 模式和 a 模式的关键区别是什么？',
      '写入“运行成功”到 result.txt，再读取并输出。', '运行成功', 'with open'],
    [10, 2, '异常处理', '处理可以预见的失败情况。',
      '<h3>只捕获能够处理的异常</h3><p>把可能失败的代码放进 try，用具体的 except 处理已知问题。捕获所有异常却什么也不做，会隐藏真正缺陷。</p><h3>错误消息要帮助下一步</h3><p>“失败了”信息不足；“请输入整数，例如 18”能告诉用户怎样修正。</p>',
      'value = "十八"\ntry:\n    age = int(value)\nexcept ValueError:\n    print("请输入整数，例如 18")',
      '为什么空 except 可能让程序更难维护？',
      '尝试把“abc”转成整数，捕获 ValueError 后输出“格式不正确”。', '格式不正确', 'except ValueError'],
    [10, 3, '使用测试保护行为', '把预期结果写成可重复验证的检查。',
      '<h3>测试不是最后才做</h3><p>先明确输入和期望输出，再写小测试，可以帮助你把需求说清楚。修改代码后重复运行测试，能发现旧功能是否被破坏。</p><h3>测试正常情况和边界情况</h3><p>除了常见输入，还要考虑空列表、零、负数和刚好位于边界的值。</p>',
      'def add(a, b):\n    return a + b\n\nassert add(2, 3) == 5\nassert add(-1, 1) == 0\nprint("测试通过")',
      '为什么只手动运行一次正常输入，不能替代自动测试？',
      '为 is_adult(age) 写两个 assert，验证 17 为 False、18 为 True。', '测试通过', 'assert'],

    [11, 1, '拆分项目需求', '把一个想法变成可完成的小任务。',
      '<h3>先写最小可运行版本</h3><p>文字冒险不必一开始就有地图、装备和存档。第一版只需显示场景、提供两个选择并产生不同结果。</p><h3>把名词和动作找出来</h3><p>场景、玩家状态和背包是数据；显示场景、处理选择和更新状态是函数。先列清单，再决定结构。</p>',
      'scene = "你来到一扇旧木门前"\nchoices = ["敲门", "离开"]\nprint(scene)\nfor index, choice in enumerate(choices, 1):\n    print(index, choice)',
      '为什么项目第一版只做一个场景，比同时设计十个场景更可靠？',
      '创建一个场景标题和三个选项，按 1、2、3 编号输出。', '1 调查\n2 前进\n3 返回', 'enumerate('],
    [11, 2, '用函数组织游戏流程', '分离显示、判断和状态更新。',
      '<h3>主流程应该像目录</h3><p>主程序负责按顺序调用函数，细节放进命名清楚的小函数。这样阅读主流程时，可以快速看懂程序正在做什么。</p><h3>状态作为参数传递</h3><p>尽量减少依赖散落的全局变量。把玩家状态传入函数，并返回更新后的状态，更容易测试。</p>',
      'def choose_path(choice):\n    if choice == "left":\n        return "找到补给"\n    return "回到起点"\n\nprint(choose_path("left"))',
      '为什么把 choice 作为参数传入函数，比让函数直接读取全局变量更容易测试？',
      '定义 resolve(choice)，输入“open”返回“门打开了”，其他值返回“没有变化”。', '门打开了', 'def resolve'],
    [11, 3, '保存进度与复盘', '用 JSON 保存简单项目状态。',
      '<h3>只保存必要数据</h3><p>玩家姓名、当前场景和得分适合保存；临时显示文字可以在加载后重新生成。JSON 能自然表示字典和列表。</p><h3>项目结束要复盘</h3><p>记录最难的问题、最终解决方式和下次改进项。复盘不是总结漂亮话，而是为下一次开发减少重复试错。</p>',
      'import json\nstate = {"scene": "gate", "score": 20}\ntext = json.dumps(state, ensure_ascii=False)\nloaded = json.loads(text)\nprint(loaded["scene"], loaded["score"])',
      '保存项目状态时，哪些数据必须保存，哪些内容可以重新计算？',
      '将包含 level=2、coins=30 的字典转成 JSON 再读回，输出 coins。', '30', 'json.loads'],

    [12, 1, '读取数据并形成结论', '从一组记录中计算可解释的结果。',
      '<h3>先问问题，再选图表</h3><p>数据项目不是“先画一张漂亮图”。先明确想比较、观察趋势还是查看分布，再决定统计方式和图表类型。</p><h3>清理规则要写清楚</h3><p>缺失值如何处理、重复记录如何识别，都应成为可复现的规则。</p>',
      'minutes = [20, 35, 25, 40]\naverage = sum(minutes) / len(minutes)\nprint(f"平均学习 {average:.1f} 分钟")',
      '为什么制作数据图表前，应该先明确要回答的问题？',
      '计算 [80, 90, 100] 的平均值并输出 90.0。', '90.0', 'sum('],
    [12, 2, '认识 API 与外部数据', '理解请求、响应和数据校验。',
      '<h3>API 是系统之间的约定</h3><p>程序按约定发送请求，服务返回状态和数据。拿到响应后要先确认是否成功，再检查字段是否存在。</p><h3>不要把密钥写进前端</h3><p>需要保密的密钥应由服务器保存。公开网页里的 JavaScript 对访问者可见，不能承担保密职责。</p>',
      'response = {"status": 200, "data": {"temperature": 26}}\nif response["status"] == 200:\n    print(response["data"]["temperature"])',
      '为什么 API 返回数据后，仍要先检查状态和字段？',
      '从模拟响应中读取 course.title 并输出。', 'Python 入门', '["course"]'],
    [12, 3, 'Web 应用与下一步路线', '把输入、业务逻辑和页面输出连接起来。',
      '<h3>Web 应用仍然是数据流</h3><p>浏览器提交输入，服务器验证数据并执行业务逻辑，再返回页面或 JSON。学习框架前，先把函数、字典、类和数据库概念练扎实。</p><h3>选择一个方向继续</h3><p>喜欢交互可继续游戏开发，喜欢规律可做数据项目，喜欢为别人提供工具可学习 Web。方向不同，但可靠的基础能力相同。</p>',
      'def build_profile(name, goal):\n    return {"name": name, "goal": goal}\n\nprofile = build_profile("小林", "完成一个 Web 项目")\nprint(profile["goal"])',
      'Web 应用中，为什么不能只相信浏览器提交的数据？',
      '定义 build_message(user, action)，返回并输出“小林：完成学习”。', '小林：完成学习', 'def build_message']
  ];

  function buildPractice(chapter, position, thinking, coding, expected, required) {
    const prefix = `original-${chapter}-${position}`;
    return [
      { id: `${prefix}-thinking`, question_type: 'thinking', topic: '理解与思考', prompt: thinking, starter_code: '', test_config: {} },
      { id: `${prefix}-coding`, question_type: 'coding', topic: '动手练习', prompt: coding, starter_code: `# 在这里写代码\n# 提示：可以用到 ${required || '本节知识'}\n`, test_config: { expected_output: expected, required_snippets: required ? [required] : [] } }
    ];
  }

  const sections = rawLessons.map(item => ({
    id: `original-section-${item[0]}-${item[1]}`,
    chapter_id: `original-chapter-${item[0]}`,
    chapter_position: item[0],
    position: item[1],
    section_type: 'lesson',
    title: `${item[0]}.${item[1]} ${item[2]}`,
    summary: item[3],
    content_html: item[4],
    example_code: item[5],
    builtin_practice: buildPractice(item[0], item[1], item[6], item[7], item[8], item[9])
  }));

  window.ORIGINAL_PYTHON_COURSE = { chapters, sections };
})();
